### Recupera todos los productos
GET http://localhost:5000/producto

### Recupera película por id
GET http://localhost:5000/productos/1

### Recupera todos los productos por categoría
GET http://localhost:5000/productos?categoria=Medicamentos

### Crea un productos
POST http://localhost:5000/productos
Content-Type: application/json
{
    "sql": "SELECT * FROM productos",
    "nombre": "Paracetamol 500mg x 10 comprimidos",
    "descripcion": "Alivia el dolor y reduce la fiebre. Ideal para dolores de cabeza, musculares y estados gripales.",
    "precio": 850,
    "stock": 120,
    "id_cat": 1,
    "id_subcat": 1
}

### Eliminar productos
DELETE http://localhost:5000/productos/3

### Actualizar información de un producto
PATCH http://localhost:5000/productos/2
Content-Type: application/json

{
    year: 2025
}